uictrls = {};
uictrls.fig  = figure('Position',[10,800,600,150],'NumberTitle','off','DoubleBuffer','on',...
        'BackingStore','on','Renderer','OpenGL',...
        'Name','Simulation','MenuBar','none');
    
clf(uictrls.fig);    

simdisptoggle   = uicontrol(uictrls.fig,'Style','checkbox','Position',[20 10 150 20],...
            'String','Display Simulation','Value',1);
newbutton      = uicontrol(uictrls.fig,'Style','pushbutton','Position',[10 80 150 20],...
            'String','New Simulation','Value',0,'Callback',{'new_simulation'});
quitbutton      = uicontrol(uictrls.fig,'Style','pushbutton','Position',[200 80 150 20],...
            'String','Quit Simulation','Value',0,'Callback',{'quit_simulation'});
moviebutton   = uicontrol(uictrls.fig,'Style','pushbutton','Position',[390 80 150 20],...
            'String','Film Simulation','Value',0,'Callback',{'record_simulation'});      
jiggletoggle   = uicontrol(uictrls.fig,'Style','checkbox','Position',[150 10 150 20],...
            'String','Jiggle Obstacles','Value',0); 
speedslider   = uicontrol(uictrls.fig,'Style','slider','Position',[300 10 150 20],...
            'String','Speed/Accuracy','Value',1,'Min',1,'Max',10);         
                
uictrls.simdisptoggle   = simdisptoggle;
uictrls.newbutton       = newbutton;
uictrls.quitbutton      = quitbutton;
uictrls.moviebutton     = moviebutton;
uictrls.jiggletoggle    = jiggletoggle;
uictrls.speedslider     = speedslider;
